#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-inventory-acl
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog
  - serverless-esbuild

custom:
  serviceName: NodeInventoryAcl
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true
  esbuild:
    platform: "node"
    target: "node20"
    bundle: true
    minify: true
    exclude: 
      - "opentracing"
      - "dd-trace"
      - "@datadog/native-metrics"
      - "@datadog/pprof"
      - '@datadog/native-appsec'
      - '@datadog/native-iast-taint-tracking'
      - '@datadog/native-iast-rewriter'
      - 'graphql/language/visitor' 
      - 'graphql/language/printer'
      - 'graphql/utilities'
      - '@aws-sdk/*'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref NewProductAddedTopic

functions:
  publishPublicEvents:
    handler: src/inventory-acl/adapters/productCreatedPublicEventHandler.handler
    environment:
      PRODUCT_ADDED_TOPIC_ARN: !Ref NewProductAddedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sqs:${NodeInventoryProductCreatedEventQueue.QueueName}"
    events:
      - sqs:
          arn:
            Fn::GetAtt: [NodeInventoryProductCreatedEventQueue, Arn]

resources:
  Resources:
    NewProductAddedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: !Sub "NodeInventoryNewProductAddedTopic-${sls:stage}"
    
    NewProductAddedTopicArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /node/inventory/new-product-added-topic
        Type: String
        Value: !Ref NewProductAddedTopic
    
    NewProductAddedTopicName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /node/inventory/new-product-added-topic-name
        Type: String
        Value: !GetAtt NewProductAddedTopic.TopicName

    NodeInventoryProductCreatedEventDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "NodeInventoryProductCreatedEventDLQ-${sls:stage}"

    NodeInventoryProductCreatedEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "NodeInventoryProductCreatedEventQueue-${sls:stage}"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "NodeInventoryProductCreatedEventDLQ"
              - "Arn"
          maxReceiveCount: 3

    ProductCreatedEventRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: "${ssm:/node/shared/event-bus-name}"
        Name: inventory-product-created
        State: ENABLED
        EventPattern:
          source:
            - !Sub "${sls:stage}.orders"
          detail-type:
            - "product.productCreated.v1"
        Targets:
          - Id: ProductCreatedEventQueue
            Arn: !GetAtt NodeInventoryProductCreatedEventQueue.Arn

    SnsToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        Queues:
          - !Ref NodeInventoryProductCreatedEventQueue
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Sid: allow-eb-send-message-messages
              Effect: Allow
              Principal:
                Service: "events.amazonaws.com"
              Resource: !GetAtt NodeInventoryProductCreatedEventQueue.Arn
              Action: SQS:SendMessage