#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-pricing-service
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog
  - serverless-esbuild

custom:
  serviceName: NodePricingService
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true
  esbuild:
    platform: "node"
    target: "node20"
    bundle: true
    minify: true
    exclude: 
      - "opentracing"
      - "dd-trace"
      - "@datadog/native-metrics"
      - "@datadog/pprof"
      - '@datadog/native-appsec'
      - '@datadog/native-iast-taint-tracking'
      - '@datadog/native-iast-rewriter'
      - 'graphql/language/visitor' 
      - 'graphql/language/printer'
      - 'graphql/utilities'
      - '@aws-sdk/*'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DOMAIN: "products"
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref ProductPricingCalculatedTopic

functions:
  handleProductCreated:
    handler: src/product-pricing-service/adapters/productCreatedPricingHandler.handler
    environment:
      PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/node/product/product-created-topic-name}"
    events:
      - sns: ${ssm:/node/product/product-created-topic}
  handleProductUpdated:
    handler: src/product-pricing-service/adapters/productUpdatedPricingHandler.handler
    environment:
      PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/node/product/product-updated-topic-name}"
    events:
      - sns: ${ssm:/node/product/product-updated-topic}

resources:
  Resources:
    ProductPricingCalculatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: !Sub "ProductPricingCalculated-${sls:stage}"
    
    ProductPricingCalculatedTopicArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /node/product/pricing-calculated-topic
        Type: String
        Value: !Ref ProductPricingCalculatedTopic
    
    ProductPricingCalculatedTopicName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /node/product/pricing-calculated-topic-name
        Type: String
        Value: !GetAtt ProductPricingCalculatedTopic.TopicName
