#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-analytics-service
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog
  - serverless-esbuild

custom:
  serviceName: NodeAnalyticsBackend
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true
  esbuild:
    platform: "node"
    target: "node20"
    bundle: true
    minify: true
    exclude: 
      - "opentracing"
      - "dd-trace"
      - "@datadog/native-metrics"
      - "@datadog/pprof"
      - '@datadog/native-appsec'
      - '@datadog/native-iast-taint-tracking'
      - '@datadog/native-iast-rewriter'
      - 'graphql/language/visitor' 
      - 'graphql/language/printer'
      - 'graphql/utilities'
      - '@aws-sdk/*'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DOMAIN: "analytics"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}

functions:
  analyticsHandler:
    handler: src/analytics-backend/adapters/analyticsEventHandler.handler
    environment:
      DD_TRACE_PROPAGATION_STYLE: "none"
    events:
      - sqs:
          arn:
            Fn::GetAtt: [NodeAnalyticsEventQueue, Arn]

resources:
  Resources:
    NodeAnalyticsEventDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "NodeAnalyticsEventDLQ-${sls:stage}"

    NodeAnalyticsEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "NodeAnalyticsEventQueue-${sls:stage}"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "NodeAnalyticsEventDLQ"
              - "Arn"
          maxReceiveCount: 3

    AnalyticsCatchAllRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: ${ssm:/node/shared/event-bus-name}
        Name: analytics-catch-all
        State: ENABLED
        EventPattern:
          source:
            - prefix: !Sub "${sls:stage}."
        Targets:
          - Id: NodeAnalyticsEventQueue
            Arn: !GetAtt NodeAnalyticsEventQueue.Arn

    EBToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref NodeAnalyticsEventQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: allow-eb-send-message-messages
              Effect: Allow
              Principal:
                Service: "events.amazonaws.com"
              Resource: !GetAtt NodeAnalyticsEventQueue.Arn
              Action: SQS:SendMessage
