#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      nodeLayerVersion: "115"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: NodePricingService
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 29
    MemorySize: 512
    Environment:
      Variables:
        ENV: !Ref Env
        DD_EXTENSION_VERSION: "next"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
    Architectures:
      - x86_64

Resources:
  ProductPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: productCreatedPricingHandler.handler
      FunctionName: !Sub ProductPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/node/product/product-created-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "node20"
        Sourcemap: true
        EntryPoints:
         - ./src/product-pricing-service/adapters/productCreatedPricingHandler.ts 
        External:
          - "opentracing"
          - "dd-trace"
          - "@datadog/native-metrics"
          - "@datadog/pprof"
          - '@datadog/native-appsec'
          - '@datadog/native-iast-taint-tracking'
          - '@datadog/native-iast-rewriter'
          - 'graphql/language/visitor' 
          - 'graphql/language/printer'
          - 'graphql/utilities'
          - '@aws-sdk/client-sns'

  ProductPricingCalculatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductPricingCalculated-${Env}"
  
  ProductPricingCalculatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /node/product/pricing-calculated-topic
      Type: String
      Value: !Ref ProductPricingCalculatedTopic