FROM --platform=${BUILDPLATFORM} rust:1-alpine3.19 as builder

ARG TARGETPLATFORM
ARG RUST_TARGET

ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN apk update && apk add pkgconfig openssl openssl-dev libc-dev musl-dev bash alpine-sdk

COPY ./scripts ./scripts

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc   
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc

COPY . .
COPY Cargo.toml Cargo.toml

# The leading '.' passes the environment variable back up to Docker build
RUN . scripts/target.sh && rustup target add $RUST_TARGET
RUN . scripts/target.sh && echo RUST_TARGET: $RUST_TARGET && cargo fetch --target $RUST_TARGET
RUN . scripts/target.sh && cargo build --release --target $RUST_TARGET --package inventory_api_web  && cp target/$RUST_TARGET/release/inventory_api_web target/inventory_api_web

RUN strip target/inventory_api_web

FROM alpine:3.19
RUN apk update \
    && apk add openssl ca-certificates libgcc

EXPOSE 8080

COPY --from=builder /target/inventory_api_web .

ENTRYPOINT ["/inventory_api_web"]