#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: RustProductPublicEventPublisher
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 512
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension:66
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_EXTENSION_VERSION: "next"
        DD_SERVICE: !Ref ServiceName
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: "INFO"
        RUST_LOG: "info"
    Architectures:
      - x86_64

Resources:
  ProductPublicEventPublisher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/product-event-publisher/lambdas/product_public_event_publisher/
      Handler: product-public-event-publisher
      FunctionName: !Sub RustProductPublicEventPublisherFunction-${Env}
      Environment:
        Variables:
          EVENT_BUS_NAME: !Sub "{{resolve:ssm:/rust/${Env}/shared/event-bus-name:1}}"
          PRODUCT_CREATED_TOPIC_ARN: !Sub "{{resolve:ssm:/rust/${Env}/product/product-created-topic:1}}"
          PRODUCT_UPDATED_TOPIC_ARN: !Sub "{{resolve:ssm:/rust/${Env}/product/product-updated-topic:1}}"
          PRODUCT_DELETED_TOPIC_ARN: !Sub "{{resolve:ssm:/rust/${Env}/product/product-deleted-topic:1}}"
          DD_SERVICE_MAPPING: !Sub "lambda_sqs:${ProductPublicEventPublisherQueue.QueueName}"
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ProductPublicEventPublisherQueue.Arn
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Sub "{{resolve:ssm:/rust/${Env}/shared/event-bus-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: rust-cargolambda
      Binary: product-public-event-publisher

  ProductPublicEventPublisherDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "ProductPublicEventPublisherDLQ-${Env}"

  ProductPublicEventPublisherQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "ProductPublicEventPublisherQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "ProductPublicEventPublisherDLQ"
            - "Arn"
        maxReceiveCount: 3

  SnsToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues:
        - !Ref ProductPublicEventPublisherQueue
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: allow-created-messages
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
            Action: SQS:SendMessage
            Condition: 
              ArnEquals:
                aws:SourceArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-created-topic:1}}"
          - Sid: allow-updated-messages
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
            Action: SQS:SendMessage
            Condition: 
              ArnEquals:
                aws:SourceArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-updated-topic:1}}"
          - Sid: allow-deleted-messages
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
            Action: SQS:SendMessage
            Condition: 
              ArnEquals:
                aws:SourceArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-deleted-topic:1}}"

  
  ProductCreatedTopicSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-created-topic:1}}"
      Endpoint: !GetAtt 
        - ProductPublicEventPublisherQueue
        - Arn
      Protocol: sqs
  
  ProductUpdatedTopicSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-updated-topic:1}}"
      Endpoint: !GetAtt 
        - ProductPublicEventPublisherQueue
        - Arn
      Protocol: sqs
  
  ProductDeletedTopicSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Sub "{{resolve:ssm:/rust/${Env}/product/product-deleted-topic:1}}"
      Endpoint: !GetAtt 
        - ProductPublicEventPublisherQueue
        - Arn
      Protocol: sqs
