#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: RustProductAcl
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 128
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension:68
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_SERVICE: !Ref ServiceName
        RUST_LOG: "info"
    Architectures:
      - x86_64

Resources:
  ProductAclStockUpdatedEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/product-acl/lambdas/inventory_stock_updated_handler/
      Handler: bootstrap
      FunctionName: !Sub RustProductAclStockUpdatedEventHandler-${Env}
      Environment:
        Variables:
          STOCK_LEVEL_UPDATED_TOPIC_ARN: !Ref InventoryStockUpdatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sqs:${RustProductStockUpdatedEventQueue.QueueName}"
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt RustProductStockUpdatedEventQueue.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt InventoryStockUpdatedTopic.TopicName
    Metadata:
      BuildMethod: rust-cargolambda
      Binary: handle_inventory_stock_updated_event
 
  InventoryStockUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "RustProductStockUpdated-${Env}"
  
  InventoryStockUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /rust/${Env}/product/stock-updated-topic
      Type: String
      Value: !Ref InventoryStockUpdatedTopic

  RustProductStockUpdatedEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "RustProductStockUpdatedEventDLQ-${Env}"

  RustProductStockUpdatedEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "RustProductStockUpdatedEventQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "RustProductStockUpdatedEventDLQ"
            - "Arn"
        maxReceiveCount: 3

  StockUpdatedEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: "{{resolve:ssm:/rust/shared/event-bus-name:1}}"
      Name: product-stock-updated
      State: ENABLED
      EventPattern:
        source:
          - !Sub "${Env}.inventory"
        detail-type:
          - "inventory.stockUpdated.v1"
      Targets:
        - Id: ProductCreatedEventQueue
          Arn: !GetAtt RustProductStockUpdatedEventQueue.Arn

  SnsToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues:
        - !Ref RustProductStockUpdatedEventQueue
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: allow-eb-send-message-messages
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Resource: !GetAtt RustProductStockUpdatedEventQueue.Arn
            Action: SQS:SendMessage
