#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: RustProductApi
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 512
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension:66
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_EXTENSION_VERSION: "next"
        DD_SERVICE: !Ref ServiceName
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: "INFO"
        RUST_LOG: "info"
    Architectures:
      - x86_64

Resources:
  ProductApiPricingWorker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/product-api/lambdas/handle_pricing_updated/
      Handler: handle-pricing-updated
      FunctionName: !Sub RustProductApiPricingWorker-${Env}
      Environment:
        Variables:
          TABLE_NAME: !Sub "{{resolve:ssm:/rust/${Env}/product/product-table-name:1}}"
      Events:
        PricingChangedTopic:
          Type: SNS
          Properties:
            Topic: !Sub "{{resolve:ssm:/rust/${Env}/product/pricing-calculated-topic:1}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "{{resolve:ssm:/rust/${Env}/product/product-table-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: rust-cargolambda
      Binary: handle-pricing-updated