asyncapi: 3.0.0
info:
  title: Product ACL
  description: The product service anti-corruption layer
  version: 1.0.0

operations:
  receiveInventoryStockUpdated:
    action: receive
    channel:
      $ref: '#/channels/inventoryStockUpdated'
    messages:
      - $ref: '#/channels/inventoryStockUpdated/messages/inventoryStockUpdatedV1'

  receiveOrderCompleted:
    action: receive
    channel:
      $ref: '#/channels/orderCompleted'
    messages:
      - $ref: '#/channels/orderCompleted/messages/orderCompletedV1'

channels:
  inventoryStockUpdated:
    address: inventory.stockUpdated.V1
    messages:
      inventoryStockUpdatedV1:
        $ref: '#/components/messages/inventoryStockUpdatedV1'
  orderCompleted:
    address: orders.orderCompleted.V1
    messages:
      orderCompletedV1:
        $ref: '#/components/messages/orderCompletedV1'

components:
  messages:
    inventoryStockUpdatedV1:
      description: 'Event triggered when the stock of a product is updated'
      x-eventcatalog-message-type: event
      x-eventcatalog-role: client
      payload:
        type: object
        properties:
          productId:
            type: string
            description: The ID of the product
          previousStockLevel:
            type: integer
            description: The previous stock level
          newStockLevel:
            type: integer
            description: The new stock level

    orderCompletedV1:
      description: 'Event received when an order is confirmed'
      x-eventcatalog-message-type: event
      x-eventcatalog-role: client
      payload:
        type: object
        properties:
          orderNumber:
            type: string
            description: The order number
          userId:
            type: string
            description: The users id