#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      extensionLayerVersion: "68"
      dotnetLayerVersion: "16"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: DotnetProductPublicEventPublisher
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  ProductCreatedPublicEventPublisher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.EventPublisher/ProductEventPublisher.Adapters/
      Handler: ProductEventPublisher.Adapters::ProductEventPublisher.Adapters.HandlerFunctions_HandleCreated_Generated::HandleCreated
      FunctionName: !Sub DotnetProductCreatedPublicEventPublisherFunction-${Env}
      Environment:
        Variables:
          EVENT_BUS_NAME: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
      Events:
        IntegrationQueue:
          Type: SNS
          Properties:
            Topic: !Sub "{{resolve:ssm:/dotnet/${Env}/product/product-created-topic:1}}"
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
  ProductUpdatedPublicEventPublisher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.EventPublisher/ProductEventPublisher.Adapters/
      Handler: ProductEventPublisher.Adapters::ProductEventPublisher.Adapters.HandlerFunctions_HandleUpdated_Generated::HandleUpdated
      FunctionName: !Sub DotnetProductUpdatedPublicEventPublisherFunction-${Env}
      Environment:
        Variables:
          EVENT_BUS_NAME: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
      Events:
        IntegrationQueue:
          Type: SNS
          Properties:
            Topic: !Sub "{{resolve:ssm:/dotnet/${Env}/product/product-updated-topic:1}}"
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
  ProductDeletedPublicEventPublisher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.EventPublisher/ProductEventPublisher.Adapters/
      Handler: ProductEventPublisher.Adapters::ProductEventPublisher.Adapters.HandlerFunctions_HandleDeleted_Generated::HandleDeleted
      FunctionName: !Sub DotnetProductDeletedPublicEventPublisherFunction-${Env}
      Environment:
        Variables:
          EVENT_BUS_NAME: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
      Events:
        Integration:
          Type: SNS
          Properties:
            Topic: !Sub "{{resolve:ssm:/dotnet/${Env}/product/product-deleted-topic:1}}"
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Sub "{{resolve:ssm:/dotnet/${Env}/shared/event-bus-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
