#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      dotnetLayerVersion: "15"
      extensionLayerVersion: "64"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: DotnetAnalyticsBackend
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  DotnetAnalyticsBackend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Analytics/Analytics.Adapters/
      Handler: Analytics.Adapters::Analytics.Adapters.HandlerFunctions_HandleEvents_Generated::HandleEvents
      FunctionName: !Sub DotnetAnalyticsBackendFunction-${Env}
      Environment:
        Variables:
          DD_TRACE_PROPAGATION_STYLE: "none"
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt DotnetAnalyticsEventQueue.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn

  DotnetAnalyticsEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "DotnetAnalyticsEventDLQ-${Env}"

  DotnetAnalyticsEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "DotnetAnalyticsEventQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DotnetAnalyticsEventDLQ"
            - "Arn"
        maxReceiveCount: 3

  AnalyticsCatchAllRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: "DotnetTracingEventBus" #"{{resolve:ssm:/dotnet/shared/event-bus-name:1}}"
      Name: analytics-catch-all
      State: ENABLED
      EventPattern:
        source:
          - prefix: !Sub "${Env}."
      Targets:
        - Id: DotnetAnalyticsEventQueue
          Arn: !GetAtt DotnetAnalyticsEventQueue.Arn

  EBToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DotnetAnalyticsEventQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: allow-eb-send-message-messages
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Resource: !GetAtt DotnetAnalyticsEventQueue.Arn
            Action: SQS:SendMessage
