#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      dotnetLayerVersion: "16"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: DotnetInventoryOrderingService
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  TopicArn:
    Type: String
    Default: '{{resolve:ssm:/dotnet/inventory/new-product-added-topic:1}}' 
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  DotnetInventoryOrderingWorkflow:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Inventory.Ordering/Inventory.Ordering.Adapters/
      Handler: Inventory.Ordering.Adapters::Inventory.Ordering.Adapters.Functions_HandleProductAdded_Generated::HandleProductAdded
      FunctionName: !Sub DotnetInventoryOrderingWorkflow-${Env}
      Environment:
        Variables:
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${TopicArn}"
          ORDERING_SERVICE_WORKFLOW_ARN: !Ref DotnetInventoryOrderingService
      Events:
        NewProductAddedTopic:
          Type: SNS
          Properties:
            Topic: !Ref TopicArn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt DotnetInventoryOrderingService.Name

  InventoryOrderingServiceLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/vendedlogs/states/DotnetInventoryOrderingServiceLogGroup-${Env}"

  DotnetInventoryOrderingService:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: cdk/Services/Inventory.Ordering/workflow/workflow.asl.json
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogDelivery"
                - "logs:CreateLogStream"
                - "logs:GetLogDelivery"
                - "logs:UpdateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutLogEvents"
                - "logs:PutResourcePolicy"
                - "logs:DescribeResourcePolicies"
                - "logs:DescribeLogGroups"
              Resource: "*"
      Logging:
        IncludeExecutionData: true
        Level: ALL
        Destinations:
           - CloudWatchLogsLogGroup: 
              LogGroupArn: !GetAtt InventoryOrderingServiceLogGroup.Arn
      Tags:
        DD_ENHANCED_METRICS: "true"
        DD_TRACE_ENABLED: "true"