#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      extensionLayerVersion: "66"
      dotnetLayerVersion: "16"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: DotnetPricingService
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  ProductCreatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Pricing/ProductPricingService.Lambda/
      Handler: ProductPricingService.Lambda::ProductPricingService.Lambda.Functions_HandleProductCreated_Generated::HandleProductCreated
      FunctionName: !Sub DotnetProductCreatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/dotnet/product/product-created-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn

  ProductUpdatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Pricing/ProductPricingService.Lambda/
      Handler: ProductPricingService.Lambda::ProductPricingService.Lambda.Functions_HandleProductUpdated_Generated::HandleProductUpdated
      FunctionName: !Sub DotnetProductUpdatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/dotnet/product/product-updated-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn

  ProductPricingCalculatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductPricingCalculated-${Env}"
  
  ProductPricingCalculatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /dotnet/product/pricing-calculated-topic
      Type: String
      Value: !Ref ProductPricingCalculatedTopic