#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      extensionLayerVersion: "68"
      dotnetLayerVersion: "16"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: DotnetProductAcl
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 1024
    Environment:
      Variables:
        ENV: !Ref Env
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: "INFO"
        DOMAIN: "product"
    Architectures:
      - x86_64

Resources:
  ProductAclStockUpdatedEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Acl/Product.Acl.Adapters/
      Handler: Product.Acl.Adapters::Product.Acl.Adapters.HandlerFunctions_HandleInventoryStockUpdate_Generated::HandleInventoryStockUpdate
      FunctionName: !Sub ProductAclStockUpdatedEventHandler-${Env}
      Environment:
        Variables:
          STOCK_UPDATED_TOPIC_ARN: !Ref InventoryStockUpdatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sqs:${DotnetProductStockUpdatedEventQueue.QueueName}"
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt DotnetProductStockUpdatedEventQueue.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt InventoryStockUpdatedTopic.TopicName
 
  InventoryStockUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "DotnetProductStockUpdated-${Env}"
  
  InventoryStockUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/inventory/stock-updated-topic
      Type: String
      Value: !Ref InventoryStockUpdatedTopic

  DotnetProductStockUpdatedEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "DotnetProductStockUpdatedEventDLQ-${Env}"

  DotnetProductStockUpdatedEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "DotnetProductStockUpdatedEventQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DotnetProductStockUpdatedEventDLQ"
            - "Arn"
        maxReceiveCount: 3

  StockUpdatedEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: "{{resolve:ssm:/dotnet/shared/event-bus-name:1}}"
      Name: product-stock-updated
      State: ENABLED
      EventPattern:
        source:
          - !Sub "${Env}.inventory"
        detail-type:
          - "inventory.stockUpdated.v1"
      Targets:
        - Id: ProductCreatedEventQueue
          Arn: !GetAtt DotnetProductStockUpdatedEventQueue.Arn

  SnsToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues:
        - !Ref DotnetProductStockUpdatedEventQueue
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: allow-eb-send-message-messages
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Resource: !GetAtt DotnetProductStockUpdatedEventQueue.Arn
            Action: SQS:SendMessage
