#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      dotnetLayerVersion: "16"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: DotnetProductApi
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        TABLE_NAME: !Ref ProductApiTable
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'POST, GET, PUT, DELETE'"
      AllowHeaders: "'*'"
      AllowOrigin: "'http://localhost:8080'"

Resources:
  ListProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Api/ProductApi.Adapters/
      Handler: ProductApi.Adapters::ProductApi.Adapters.ApiFunctions_ListProducts_Generated::ListProducts
      FunctionName: !Sub DotnetListProductFunctions-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref ProductApiTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Api/ProductApi.Adapters/
      Handler: ProductApi.Adapters::ProductApi.Adapters.ApiFunctions_GetProduct_Generated::GetProduct
      FunctionName: !Sub DotnetGetProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product/{productId}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref ProductApiTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
              
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Api/ProductApi.Adapters/
      Handler: ProductApi.Adapters::ProductApi.Adapters.ApiFunctions_CreateProduct_Generated::CreateProduct
      FunctionName: !Sub DotnetCreateProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product
            Method: post
      Environment:
        Variables:
          PRODUCT_CREATED_TOPIC_ARN: !Ref ProductCreatedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductCreatedTopic.TopicName
            
  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Api/ProductApi.Adapters/
      Handler: ProductApi.Adapters::ProductApi.Adapters.ApiFunctions_UpdateProduct_Generated::UpdateProduct
      FunctionName: !Sub DotnetUpdateProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product
            Method: put
      Environment:
        Variables:
          PRODUCT_UPDATED_TOPIC_ARN: !Ref ProductUpdatedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductUpdatedTopic.TopicName
            
  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Product.Api/ProductApi.Adapters/
      Handler: ProductApi.Adapters::ProductApi.Adapters.ApiFunctions_DeleteProduct_Generated::DeleteProduct
      FunctionName: !Sub DotnetDeleteProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product/{productId}
            Method: delete
      Environment:
        Variables:
          PRODUCT_DELETED_TOPIC_ARN: !Ref ProductDeletedTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductDeletedTopic.TopicName
  
  ProductCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "DotnetProductCreatedTopic-${Env}"
  ProductUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "DotnetProductUpdatedTopic-${Env}"
  ProductDeletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "DotnetProductDeletedTopic-${Env}"
  
  ProductCreatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/product/product-created-topic
      Type: String
      Value: !Ref ProductCreatedTopic
  ProductUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/product/product-updated-topic
      Type: String
      Value: !Ref ProductUpdatedTopic
  ProductDeletedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/product/product-deleted-topic
      Type: String
      Value: !Ref ProductDeletedTopic
  ProductApiTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/product/product-table-name
      Type: String
      Value: !Ref ProductApiTable

  ProductApiTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DotnetProducts-${Env}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

  ApiEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /dotnet/${Env}/product/api-endpoint
      Type: String
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

Outputs:
  DotnetProductApiEndpoint:
    Description: Product API Endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: DotnetProductApiEndpoint