#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-pricing-service
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog

custom:
  serviceName: JavaPricingService
  datadog:
    apiKeySecretArn: ${param:DD_SECRET_ARN}
    site: datadoghq.eu
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: java21
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DD_SERVERLESS_APPSEC_ENABLED: "true"
    DD_LOGS_INJECTION: "true"
    MAIN_CLASS: com.analytics.FunctionConfiguration
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_SECRET_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref ProductPricingCalculatedTopic

functions:
  handleProductCreated:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/java/product/product-created-topic-name}"
      spring_cloud_function_definition: handleProductCreated
    package:
      artifact: ./product-pricing/target/com.product.pricing-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sns: ${ssm:/java/product/product-created-topic}

  handleProductUpdated:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/java/product/product-updated-topic-name}"
      spring_cloud_function_definition: handleProductUpdated
    package:
      artifact: ./product-pricing/target/com.product.pricing-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sns: ${ssm:/java/product/product-updated-topic}

resources:
  Resources:
    ProductPricingCalculatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: !Sub "ProductPricingCalculated-${sls:stage}"
    
    ProductPricingCalculatedTopicArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /java/product/pricing-calculated-topic
        Type: String
        Value: !Ref ProductPricingCalculatedTopic
    
    ProductPricingCalculatedTopicName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /java/product/pricing-calculated-topic-name
        Type: String
        Value: !GetAtt ProductPricingCalculatedTopic.TopicName
