#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-product-event-publisher
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog

custom:
  serviceName: JavaProductPublicEventPublisher
  datadog:
    apiKeySecretArn: ${param:DD_SECRET_ARN}
    site: datadoghq.eu
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: 64
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: java21
  memorySize: 2048
  timeout: 29
  logRetentionInDays: 1
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DD_SERVERLESS_APPSEC_ENABLED: "true"
    DD_LOGS_INJECTION: "true"
    MAIN_CLASS: com.product.publisher.FunctionConfiguration
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_SECRET_ARN}
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/${ssm:/java/shared/event-bus-name}"

functions:
  publishPublicEvents:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      EVENT_BUS_NAME: "${ssm:/java/shared/event-bus-name}"
      PRODUCT_CREATED_TOPIC_ARN: "${ssm:/java/product/product-created-topic}"
      PRODUCT_UPDATED_TOPIC_ARN: "${ssm:/java/product/product-updated-topic}"
      PRODUCT_DELETED_TOPIC_ARN: "${ssm:/java/product/product-deleted-topic}"
      DD_SERVICE_MAPPING: !Sub "lambda_sqs:${ProductPublicEventPublisherQueue.QueueName}"
      spring_cloud_function_definition: handleInternalEvents
    package:
      artifact: ./product-event-publisher/target/com.product.publisher-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ProductPublicEventPublisherQueue, Arn]

resources:
  Resources:
    ProductPublicEventPublisherDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "ProductPublicEventPublisherDLQ-${sls:stage}"

    ProductPublicEventPublisherQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "ProductPublicEventPublisherQueue-${sls:stage}"
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ProductPublicEventPublisherDLQ.Arn
          maxReceiveCount: 3

    SnsToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        Queues:
          - !Ref ProductPublicEventPublisherQueue
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Sid: allow-created-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/java/product/product-created-topic:1}}"
            - Sid: allow-updated-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/java/product/product-updated-topic:1}}"
            - Sid: allow-deleted-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/java/product/product-deleted-topic:1}}"

    
    ProductCreatedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/java/product/product-created-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
    
    ProductUpdatedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/java/product/product-updated-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
    
    ProductDeletedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/java/product/product-deleted-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
