#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-inventory-acl
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog

custom:
  serviceName: JavaProductAcl
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: 65
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: java21
  memorySize: 2048
  timeout: 29
  logRetentionInDays: 1
  environment:
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DD_LOGS_INJECTION: "true"
    MAIN_CLASS: com.inventory.acl.FunctionConfiguration
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref ProductStockUpdatedTopic

functions:
  publishPublicEvents:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      PRODUCT_ADDED_TOPIC_ARN: !Ref ProductStockUpdatedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sqs:${JavaInventoryProductCreatedEventQueue.QueueName}"
      spring_cloud_function_definition: handleStockUpdatedEvent
    package:
      artifact: ./product-acl/target/com.product.acl-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sqs:
          arn:
            Fn::GetAtt: [JavaProductStockUpdatedEventQueue, Arn]

resources:
  Resources:
    ProductStockUpdatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: !Sub "JavaProductStockUpdated-${Env}"

    ProductStockUpdatedTopicArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: !Sub /java/${Env}/product/product-stock-updated-topic
        Type: String
        Value: !Ref ProductStockUpdatedTopic

    JavaProductStockUpdatedEventDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "JavaProductStockUpdatedEventDLQ-${Env}"

    JavaProductStockUpdatedEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "JavaProductStockUpdatedEventQueue-${Env}"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "JavaProductStockUpdatedEventDLQ"
              - "Arn"
          maxReceiveCount: 3

    InventoryStockUpdatedEventRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: !Sub "{{resolve:ssm:/java/${Env}/shared/event-bus-name:1}}"
        Name: product-stock-updated
        State: ENABLED
        EventPattern:
          source:
            - !Sub "${Env}.inventory"
          detail-type:
            - "inventory.stockUpdated.v1"
        Targets:
          - Id: ProductCreatedEventQueue
            Arn: !GetAtt JavaProductStockUpdatedEventQueue.Arn

    SnsToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref JavaProductStockUpdatedEventQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: allow-eb-send-message-messages
              Effect: Allow
              Principal:
                Service: "events.amazonaws.com"
              Resource: !GetAtt JavaProductStockUpdatedEventQueue.Arn
              Action: SQS:SendMessage