#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      extensionLayerVersion: "65"
      javaLayerVersion: "15"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: JavaPricingService
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        MAIN_CLASS: com.product.pricing.FunctionConfiguration
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  ProductCreatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-pricing/target/com.product.pricing-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub ProductCreatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
          spring_cloud_function_definition: handleProductCreated
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/java/product/product-created-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      SkipBuild: True

  ProductUpdatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-pricing/target/com.product.pricing-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub ProductUpdatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
          spring_cloud_function_definition: handleProductUpdated
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/java/product/product-updated-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      SkipBuild: True

  ProductPricingCalculatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "ProductPricingCalculated-${Env}"
  
  ProductPricingCalculatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/pricing-calculated-topic
      Type: String
      Value: !Ref ProductPricingCalculatedTopic