#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      javaLayerVersion: "15"
      extensionLayerVersion: "64"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: JavaAnalyticsBackend
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        MAIN_CLASS: com.analytics.FunctionConfiguration
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  JavaAnalyticsBackend:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./analytics-backend/target/com.analytics-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub JavaAnalyticsBackendFunction-${Env}
      Environment:
        Variables:
          DD_TRACE_PROPAGATION_STYLE: "none"
          spring_cloud_function_definition: handleEvents
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt JavaAnalyticsEventQueue.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      SkipBuild: True

  JavaAnalyticsEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "JavaAnalyticsEventDLQ-${Env}"

  JavaAnalyticsEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "JavaAnalyticsEventQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "JavaAnalyticsEventDLQ"
            - "Arn"
        maxReceiveCount: 3

  AnalyticsCatchAllRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: "JavaTracingEventBus" #"{{resolve:ssm:/java/shared/event-bus-name:1}}"
      Name: analytics-catch-all
      State: ENABLED
      EventPattern:
        source:
          - prefix: !Sub "${Env}."
      Targets:
        - Id: JavaAnalyticsEventQueue
          Arn: !GetAtt JavaAnalyticsEventQueue.Arn

  EBToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref JavaAnalyticsEventQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: allow-eb-send-message-messages
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Resource: !GetAtt JavaAnalyticsEventQueue.Arn
            Action: SQS:SendMessage
