#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      javaLayerVersion: "15"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: JavaInventoryOrderingService
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        MAIN_CLASS: com.inventory.ordering.FunctionConfiguration
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  JavaInventoryOrderingWorkflow:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./inventory-ordering-service/target/com.inventory.ordering-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub JavaInventoryOrderingWorkflow-${Env}
      Environment:
        Variables:
          ORDERING_SERVICE_WORKFLOW_ARN: !Ref JavaInventoryOrderingService
          spring_cloud_function_definition: handleNewProductAdded
      Events:
        NewProductAddedTopic:
          Type: SNS
          Properties:
            Topic: !Sub '{{resolve:ssm:/java/${Env}/inventory/new-product-added-topic:1}}' 
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt JavaInventoryOrderingService.Name
    Metadata:
      SkipBuild: True

  InventoryOrderingServiceLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/vendedlogs/states/JavaInventoryOrderingServiceLogGroup-${Env}"

  JavaInventoryOrderingService:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: cdk/src/main/java/com/cdk/inventory/ordering/workflows/workflow.sample.asl.json
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogDelivery"
                - "logs:CreateLogStream"
                - "logs:GetLogDelivery"
                - "logs:UpdateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutLogEvents"
                - "logs:PutResourcePolicy"
                - "logs:DescribeResourcePolicies"
                - "logs:DescribeLogGroups"
              Resource: "*"
      Logging:
        IncludeExecutionData: true
        Level: ALL
        Destinations:
           - CloudWatchLogsLogGroup: 
              LogGroupArn: !GetAtt InventoryOrderingServiceLogGroup.Arn
      Tags:
        DD_ENHANCED_METRICS: "true"
        DD_TRACE_ENABLED: "true"

  InventoryOrderingWorkflowArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /java/${Env}/inventory-ordering/state-machine-arn
      Type: String
      Value: !Ref NodeInventoryOrderingService