#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      javaLayerVersion: "15"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: JavaProductApi
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        TABLE_NAME: !Ref ProductApiTable
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        MAIN_CLASS: com.product.api.FunctionConfiguration
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'POST, GET, PUT, DELETE'"
      AllowHeaders: "'*'"
      AllowOrigin: "'http://localhost:8080'"

Resources:
  ListProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub ListProductsFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties:
            Path: /product
            Method: get
      Environment:
        Variables:
          spring_cloud_function_definition: handleListProducts
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref ProductApiTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      SkipBuild: True
  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub GetProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product/{productId}
            Method: get
      Environment:
        Variables:
          spring_cloud_function_definition: handleGetProduct
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref ProductApiTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      SkipBuild: True
              
  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub CreateProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product
            Method: post
      Environment:
        Variables:
          PRODUCT_CREATED_TOPIC_ARN: !Ref ProductCreatedTopic
          spring_cloud_function_definition: handleCreateProduct
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductCreatedTopic.TopicName
    Metadata:
      SkipBuild: True
            
  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub UpdateProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product
            Method: put
      Environment:
        Variables:
          PRODUCT_UPDATED_TOPIC_ARN: !Ref ProductUpdatedTopic
          spring_cloud_function_definition: handleUpdateProduct
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductUpdatedTopic.TopicName
    Metadata:
      SkipBuild: True
            
  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-api/target/com.product.api-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub DeleteProductFunction-${Env}
      Events:
        GetProduct:
          Type: Api
          Properties: 
            Path: /product/{productId}
            Method: delete
      Environment:
        Variables:
          PRODUCT_DELETED_TOPIC_ARN: !Ref ProductDeletedTopic
          spring_cloud_function_definition: handleDeleteProduct
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !GetAtt ProductApiTable.Arn
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductDeletedTopic.TopicName
    Metadata:
      SkipBuild: True
  
  ProductCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "JavaProductCreatedTopic-${Env}"
  ProductUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "JavaProductUpdatedTopic-${Env}"
  ProductDeletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "JavaProductDeletedTopic-${Env}"
  
  ProductCreatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-created-topic
      Type: String
      Value: !Ref ProductCreatedTopic
  ProductUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-updated-topic
      Type: String
      Value: !Ref ProductUpdatedTopic
  ProductDeletedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-deleted-topic
      Type: String
      Value: !Ref ProductDeletedTopic
  ProductApiTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /java/product/product-table-name
      Type: String
      Value: !Ref ProductApiTable

  ProductApiTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub JavaProducts-${Env}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: PK
          KeyType: HASH

  ApiEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /java/${Env}/product/api-endpoint
      Type: String
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"

Outputs:
  JavaProductApiEndpoint:
    Description: Product API Endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: JavaProductApiEndpoint