#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref DDApiKeySecretArn
      javaLayerVersion: "15"
      extensionLayerVersion: "66"
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true

Parameters:
  ServiceName:
    Type: String
    Default: JavaProductAcl
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: java21
    Timeout: 29
    MemorySize: 2048
    Environment:
      Variables:
        ENV: !Ref Env
        DD_LOGS_INJECTION: "true"
        DD_EXTENSION_VERSION: next
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
        MAIN_CLASS: com.inventory.acl.FunctionConfiguration
        AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    Architectures:
      - x86_64

Resources:
  ProductInventoryStockUpdatedEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./product-acl/target/com.product.acl-0.0.1-SNAPSHOT-aws.jar
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      FunctionName: !Sub JavaInventoryStockUpdatedEventHandler-${Env}
      Environment:
        Variables:
          PRODUCT_STOCK_UPDATED_TOPIC_ARN: !Ref ProductStockUpdatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sqs:${JavaProductStockUpdatedEventQueue.QueueName}"
          spring_cloud_function_definition: handleStockUpdatedEvent
      Events:
        IntegrationQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt JavaProductStockUpdatedEventQueue.Arn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductStockUpdatedTopic.TopicName
    Metadata:
      SkipBuild: True
 
  ProductStockUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "JavaProductStockUpdated-${Env}"
  
  ProductStockUpdatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /java/${Env}/product/product-stock-updated-topic
      Type: String
      Value: !Ref ProductStockUpdatedTopic

  JavaProductStockUpdatedEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "JavaProductStockUpdatedEventDLQ-${Env}"

  JavaProductStockUpdatedEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "JavaProductStockUpdatedEventQueue-${Env}"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "JavaProductStockUpdatedEventDLQ"
            - "Arn"
        maxReceiveCount: 3

  InventoryStockUpdatedEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Sub "{{resolve:ssm:/java/${Env}/shared/event-bus-name:1}}"
      Name: product-stock-updated
      State: ENABLED
      EventPattern:
        source:
          - !Sub "${Env}.inventory"
        detail-type:
          - "inventory.stockUpdated.v1"
      Targets:
        - Id: ProductCreatedEventQueue
          Arn: !GetAtt JavaProductStockUpdatedEventQueue.Arn

  SnsToQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues:
        - !Ref JavaProductStockUpdatedEventQueue
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Sid: allow-eb-send-message-messages
            Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Resource: !GetAtt JavaProductStockUpdatedEventQueue.Arn
            Action: SQS:SendMessage
