#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-inventory-ordering-service
frameworkVersion: "3"

plugins:
  - serverless-step-functions
  - serverless-plugin-datadog

custom:
  serviceName: RustInventoryOrderingService
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: provided.al2023
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    RUST_LOG: "info"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:inventoryOrderingWorkflow${sls:stage}

functions:
  startOrderingWorkflow:
    handler: bootstrap
    package:
      artifact: ./out/inventoryOrderingWorkflowTrigger/inventoryOrderingWorkflowTrigger.zip
      individually: true
    environment:
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/rust/inventory/new-product-added-topic-name}"
      ORDERING_SERVICE_WORKFLOW_ARN: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:inventoryOrderingWorkflow${sls:stage}
    events:
      - sns: ${ssm:/rust/inventory/new-product-added-topic}

stepFunctions:
  stateMachines:
    inventoryOrderingWorkflow:
      name: inventoryOrderingWorkflow${sls:stage}
      definition: ${file(lib/inventory-ordering-service/workflows/workflow.sample.asl.json)}
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [InventoryOrderingServiceLogGroup, Arn]
      tags:
          DD_ENHANCED_METRICS: "true"
          DD_TRACE_ENABLED: "true"

resources:
  Resources:
    InventoryOrderingServiceLogGroup: 
      Type: AWS::Logs::LogGroup
      Properties: 
        RetentionInDays: 1
        LogGroupName: !Sub "/aws/vendedlogs/states/RustInventoryOrderingServiceLogGroup-${sls:stage}"