#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-product-event-publisher
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog

custom:
  serviceName: RustProductPublicEventPublisher
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: latest
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: provided.al2023
  environment:
    DD_EXTENSION_VERSION: "next"
    ENV: ${sls:stage}
    RUST_LOG: "info"

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:event-bus/${ssm:/rust/shared/event-bus-name}"

functions:
  publishPublicEvents:
    handler: bootstrap
    package:
      artifact: ./out/publicEventPublisherFunction/publicEventPublisherFunction.zip
      individually: true
    environment:
      EVENT_BUS_NAME: "${ssm:/rust/shared/event-bus-name}"
      PRODUCT_CREATED_TOPIC_ARN: "${ssm:/rust/product/product-created-topic}"
      PRODUCT_UPDATED_TOPIC_ARN: "${ssm:/rust/product/product-updated-topic}"
      PRODUCT_DELETED_TOPIC_ARN: "${ssm:/rust/product/product-deleted-topic}"
      DD_SERVICE_MAPPING: !Sub "lambda_sqs:${ProductPublicEventPublisherQueue.QueueName}"
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ProductPublicEventPublisherQueue, Arn]

resources:
  Resources:
    ProductPublicEventPublisherDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "ProductPublicEventPublisherDLQ-${sls:stage}"

    ProductPublicEventPublisherQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "ProductPublicEventPublisherQueue-${sls:stage}"
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ProductPublicEventPublisherDLQ.Arn
          maxReceiveCount: 3

    SnsToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        Queues:
          - !Ref ProductPublicEventPublisherQueue
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Sid: allow-created-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/rust/product/product-created-topic:1}}"
            - Sid: allow-updated-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/rust/product/product-updated-topic:1}}"
            - Sid: allow-deleted-messages
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt ProductPublicEventPublisherQueue.Arn
              Action: SQS:SendMessage
              Condition: 
                ArnEquals:
                  aws:SourceArn: "{{resolve:ssm:/rust/product/product-deleted-topic:1}}"

    
    ProductCreatedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/rust/product/product-created-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
    
    ProductUpdatedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/rust/product/product-updated-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
    
    ProductDeletedTopicSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: "${ssm:/rust/product/product-deleted-topic}"
        Endpoint: !GetAtt ProductPublicEventPublisherQueue.Arn
        Protocol: sqs
