services:
  inventory-api:
    image: "dd-serverless-sample-app-inventory-java"
    container_name: inventory-api
    ports:
      - "8080:8080"
    environment:
      - ENV=local
  datadog:
    container_name: dd-agent
    image: "datadog/agent"
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8126:8126" # APM
      - "8125:8125/udp" # DogStatsD
    environment:
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true # enables agent to receive custom metrics from other containers
      - DD_APM_ENABLED=true # enables tracing
      - DD_APM_NON_LOCAL_TRAFFIC=true # enables agent to receive traces from other containers
      - DD_AGENT_HOST=dd-agent # allows web container to forward traces to agent
      - DD_SITE=${DD_SITE} # determines datadog instance to send data to (e.g change to datadoghq.eu for EU1)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal