#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters: 
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKey: 
    Type: String

Resources:
  SharedEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: !Sub "SharedEventBus-${Env}"

  SharedEventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Env}/shared/event-bus-name
      Type: String
      Value: !Ref SharedEventBus

  SharedEventBusArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Env}/shared/event-bus-arn
      Type: String
      Value: !GetAtt SharedEventBus.Arn

  JwtSecretAccessKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Env}/shared/secret-access-key
      Type: String
      Value: "This is a sample secret key - please don't use in production environment.'"

  DDApiKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub /${Env}/shared/serverless-sample-dd-api-key
      SecretString: !Ref DDApiKey