#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters: 
  ServiceName: 
    Type: String
    Default: GoPricingService
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 512
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:68
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_SERVICE: !Ref ServiceName
        DD_CAPTURE_LAMBDA_PAYLOAD: "true"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
    Architectures:
      - arm64

Resources:
  ProductCreatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub GoProductCreatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/go/product/product-created-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: makefile
      
  ProductUpdatedPricingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub GoProductUpdatedPricingServiceFunction-${Env}
      Environment:
        Variables:
          PRICE_CALCULATED_TOPIC_ARN: !Ref ProductPricingCalculatedTopic
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${ProductPricingCalculatedTopic.TopicName}"
      Events:
        ProductCreated:
          Type: SNS
          Properties: 
            Topic: '{{resolve:ssm:/go/product/product-updated-topic:1}}' 
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ProductPricingCalculatedTopic.TopicName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - dynamodb:GetItem
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: makefile

  ProductPricingCalculatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "GoProductPricingCalculated-${Env}"
  
  ProductPricingCalculatedTopicArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /go/product/pricing-calculated-topic
      Type: String
      Value: !Ref ProductPricingCalculatedTopic