#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: GoProductApi
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  TopicArn:
    Type: String
    Default: "{{resolve:ssm:/go/product/pricing-calculated-topic:1}}"
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 512
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:66
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_SERVICE: !Ref ServiceName
        DD_SERVERLESS_APPSEC_ENABLED: "true"
        DD_CAPTURE_LAMBDA_PAYLOAD: "true"
        TABLE_NAME: !Ref ProductApiTable
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
    Architectures:
      - arm64

Resources:
  ProductApiPricingWorker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub GoProductApiPricingWorker-${Env}
      Environment:
        Variables:
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${TopicArn}"
          TABLE_NAME: "{{resolve:ssm:/go/product/product-table-name:1}}"
      Events:
        PricingChangedTopic:
          Type: SNS
          Properties:
            Topic: !Ref TopicArn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{resolve:ssm:/go/product/product-table-name:1}}"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
    Metadata:
      BuildMethod: makefile