#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters: 
  Env: 
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest

Resources:
  GoSharedEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: !Sub "GoTracingEventBus-${Env}"

  SharedEventBusNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /go/shared/event-bus-name
      Type: String
      Value: !Ref GoSharedEventBus