#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Parameters:
  ServiceName:
    Type: String
    Default: GoInventoryOrderingService
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDApiKeySecretArn:
    Type: String
  TopicArn:
    Type: String
    Default: '{{resolve:ssm:/go/inventory/new-product-added-topic:1}}' 
  DDSite:
    Type: String

Globals:
  Function:
    Runtime: provided.al2023
    Timeout: 29
    MemorySize: 512
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Extension-ARM:68
    Environment:
      Variables:
        ENV: !Ref Env
        DD_ENV: !Ref Env
        DD_API_KEY_SECRET_ARN: !Ref DDApiKeySecretArn
        DD_SITE: !Ref DDSite
        DD_VERSION: !Ref CommitHash
        DD_SERVICE: !Ref ServiceName
        DD_SERVERLESS_APPSEC_ENABLED: "true"
        POWERTOOLS_SERVICE_NAME: !Ref ServiceName
        POWERTOOLS_LOG_LEVEL: 'INFO'
    Architectures:
      - arm64

Resources:
  InventoryOrderingWorkflow:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      FunctionName: !Sub GoInventoryOrderingWorkflow-${Env}
      Environment:
        Variables:
          DD_SERVICE_MAPPING: !Sub "lambda_sns:${TopicArn}"
          ORDERING_SERVICE_WORKFLOW_ARN: !Ref GoInventoryOrderingService
      Events:
        NewProductAddedTopic:
          Type: SNS
          Properties:
            Topic: !Ref TopicArn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DDApiKeySecretArn
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt GoInventoryOrderingService.Name
    Metadata:
      BuildMethod: makefile

  InventoryOrderingServiceLogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 1
      LogGroupName: !Sub "/aws/vendedlogs/states/GoInventoryOrderingServiceLogGroup-${Env}"

  GoInventoryOrderingService:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: lib/inventory-ordering-service/workflows/ordering-workflow-setStock.asl.json
      DefinitionSubstitutions:
        TableName: "{{resolve:ssm:/go/inventory-api/table-name:1}}"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogDelivery"
                - "logs:CreateLogStream"
                - "logs:GetLogDelivery"
                - "logs:UpdateLogDelivery"
                - "logs:DeleteLogDelivery"
                - "logs:ListLogDeliveries"
                - "logs:PutLogEvents"
                - "logs:PutResourcePolicy"
                - "logs:DescribeResourcePolicies"
                - "logs:DescribeLogGroups"
              Resource: "*"
        - DynamoDBWritePolicy:
            TableName: "{{resolve:ssm:/go/inventory-api/table-name:1}}"
      Logging:
        IncludeExecutionData: true
        Level: ALL
        Destinations:
           - CloudWatchLogsLogGroup: 
              LogGroupArn: !GetAtt InventoryOrderingServiceLogGroup.Arn
      Tags:
        DD_ENHANCED_METRICS: "true"
        DD_TRACE_ENABLED: "true"

  InventoryOrderingWorkflowArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /go/${Env}/inventory-ordering/state-machine-arn
      Type: String
      Value: !Ref GoInventoryOrderingService