services:
  web:
    build: .
    environment:
      - AWS_REGION=eu-west-1
      - TABLE_NAME=NodeInventoryApi-dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - "3000:3000"