name: Deploy Build Image

on:
  push:
    paths:
      - build-image/**
      - cdk-deploy-all.sh
      - cdk-destroy.sh
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-build-image:
    runs-on: ubuntu-latest
    concurrency:
      group: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
      - name: Get Commit Info
        id: get_sha
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.BUILD_IMAGE_ECR_REPOSITORY }}/${{ secrets.BUILD_IMAGE_NAME }}
          tags: |
            latest
            ${{ env.COMMIT_SHA }}

      - uses: aws-actions/amazon-ecr-login@v2
        name: Login to Amazon ECR Public
        id: login-ecr-public
        with:
          registry-type: public

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./build-image
          file: ./build-image/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}