name: Deploy Orders Service

on:
  push:
    paths:
      - src/order-service/**
    branches:
      - "main"
  pull_request:
    paths:
      - src/order-service/**
    branches:
      - "main"
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
      - name: Login to Amazon ECR public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Build
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "us-east-1"
        run: |
          cd src/order-service
          make build
      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k4y9x2e7
          REPOSITORY: dd-serverless-sample-app-dotnet
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd src/order-service
          docker build -f Dockerfile -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
  deploy-tf:
    runs-on: ubuntu-latest
    concurrency:
      group: tf-networked
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-2"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Build
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "tf-${{ env.sha_short }}"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          cd src/order-service
          make build
      - name: Deploy to ephermal environment
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "tf-${{ env.sha_short }}"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          cd src/order-service
          make tf-apply
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Integration test ephermal environment
        shell: bash
        env:
          ENV: "tf-${{ env.sha_short }}"
          AWS_REGION: "eu-west-2"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy ephermal environment
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "tf-${{ env.sha_short }}"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          cd src/order-service
          make tf-destroy
      - name: Deploy to dev
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_2_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          cd src/order-service
          make tf-apply
      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      - name: Integration test dev
        shell: bash
        env:
          ENV: "dev"
          AWS_REGION: "eu-west-2"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy dev
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          cd src/order-service
          make tf-destroy

  deploy-cdk:
    runs-on: ubuntu-latest
    concurrency:
      group: cdk-networked
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "cdk-${{ env.sha_short }}"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
        run: |
          cd src/order-service
          make cdk-deploy
      - name: Integration test dev
        shell: bash
        env:
          ENV: "cdk-${{ env.sha_short }}"
          AWS_REGION: "eu-west-1"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "cdk-${{ env.sha_short }}"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
        run: |
          cd src/order-service
          make cdk-destroy
      - name: Deploy to dev AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
        run: |
          cd src/order-service
          make cdk-deploy
      - name: Integration test dev
        shell: bash
        env:
          ENV: "dev"
          AWS_REGION: "eu-west-1"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy dev
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
        run: |
          cd src/order-service
          make cdk-destroy

  deploy-sam:
    runs-on: ubuntu-latest
    concurrency:
      group: sam-networked
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-central-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "sam-${{ env.sha_short }}"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make sam
      - name: Integration test dev
        shell: bash
        env:
          ENV: "sam-${{ env.sha_short }}"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "sam-${{ env.sha_short }}"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make sam-destroy
      - name: Deploy to dev
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make sam
      - name: Integration test dev
        shell: bash
        env:
          ENV: "dev"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make integration-test
      - name: Destroy dev
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-central-1"
        run: |
          cd src/order-service
          make sam-destroy
