name: Deploy Shared Services

on:
  push:
    paths:
      - src/shared-infra/**
    branches:
      - "main"
  pull_request:
    paths:
      - src/shared-infra/**
    branches:
      - "main"
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-tf:
    runs-on: ubuntu-latest
    concurrency:
      group: tf-shared-services
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-2"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Terraform apply
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_SITE: "datadoghq.com"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: |
          cd src/shared-infra
          make tf-apply

  deploy-cdk:
    runs-on: ubuntu-latest
    concurrency:
      group: cdk-shared-services
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "20"
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_SITE: "datadoghq.com"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: |
          cd src/shared-infra
          npm i
          make cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.PRODUCTION_AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-2"
      - name: Deploy to AWS Prod
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "prod"
          DD_SITE: "datadoghq.com"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: |
          cd src/shared-infra
          npm i
          make cdk

  deploy-sam:
    runs-on: ubuntu-latest
    concurrency:
      group: sam-shared-services
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "22"
      - uses: aws-actions/setup-sam@0578b2f57e540e67233c3ce0c5477ee36938ff3d # v1.0.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-central-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_SITE: "datadoghq.com"
          AWS_REGION: "eu-central-1"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: |
          cd src/shared-infra
          make sam

  deploy-sls-framework:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "22"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-2"
      - name: Install Serverless Framework
        run: |
          npm install -g serverless@3.40.0
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "dev"
          DD_SITE: "datadoghq.com"
          AWS_REGION: "us-east-2"
          DD_API_KEY: ${{secrets.DD_API_KEY}}
        run: |
          cd src/shared-infra
          npm i
          make serverless-framework
