name: Go CDK Deploy

on:
    push:
      paths:
        - src/go/src/**
        - src/go/cdk/**
      branches:
          - 'main'
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package-and-test:
    runs-on: ubuntu-latest
    concurrency:
        group: go-cdk
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install CDK
        run: |
          npm install -g aws-cdk
      - uses: actions/setup-go@v5
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
        run: |
          make cdk-go
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: serverless-sample-go-cdk
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.eu
      - name: Run end to end test
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          RUNTIME: "Go"
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
        run: |
          make end-to-end-test
      - name: Teardown
        shell: bash
        if: always()
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
        run: |
          make cdk-go-destroy
          