name: Java Terraform Deploy

on:
    push:
      paths:
        - src/java/inventory-acl/**
        - src/java/inventory-ordering-service/**
        - src/java/analytics-backend/**
        - src/java/product-api/**
        - src/java/product-event-publisher/**
        - src/java/product-pricing/**
        - src/java/infra/**
      branches:
          - 'main'
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package-and-test:
    runs-on: ubuntu-latest
    concurrency:
        group: java-tf
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Set up Java 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "eu-west-2"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Package Java application
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_2_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          make package-java
      - name: Terraform apply
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_2_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          make tf-java
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: serverless-sample-java-tf
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.eu
      - name: Run end to end test
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          RUNTIME: "Java"
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
        run: |
          make end-to-end-test
      - name: Teardown test resources
        if: always()
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.EU_WEST_2_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "eu-west-2"
          TF_STATE_BUCKET_NAME: ${{secrets.TF_STATE_BUCKET_NAME}}
        run: |
          make tf-java-destroy
          