name: Java SAM Deploy

on:
    push:
      paths:
        - src/java/src/**
        - src/java/template*.yaml
      branches:
          - 'main'
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package-and-test:
    runs-on: ubuntu-latest
    concurrency:
        group: dotnet-java
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Set up Java 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"
      - name: Set Commit Hash Environment Variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Compile JAR files
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "us-east-1"
        run: |
          make package-java
      - name: Deploy to AWS
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          AWS_REGION: "us-east-1"
        run: |
          make sam-java
      - name: Configure Datadog Test Visibility
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          service: serverless-sample-java-cdk
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.eu
      - name: Run end to end test
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
          RUNTIME: "Java"
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }}
        run: |
          make end-to-end-test
      - name: Teardown
        if: always()
        shell: bash
        env:
          COMMIT_HASH: ${{ env.sha_short }}
          ENV: "test"
          DD_API_KEY_SECRET_ARN: ${{secrets.US_EAST_1_DD_API_KEY_SECRET_ARN}}
          DD_SITE: "datadoghq.eu"
        run: |
          make sam-java-destroy
          