name: Static Analysis

on:
    schedule:
      - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  dotnet-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-dotnet
      directory: src/order-service
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}

  java-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-java
      directory: src/inventory-service
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}

  rust-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-rust
      directory: src/user-management-service
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}

  go-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-go
      directory: src/product-management-service
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}

  nodejs-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-nodejs
      directory: src/loyalty-point-service
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}

  frontend-static-analysis:
    uses: DataDog/serverless-sample-app/.github/workflows/shared-static-analysis.yml@main
    with:
      service-name: serverless-sample-frontend
      directory: src/frontend
    secrets:
      dd_api_key: ${{secrets.DD_API_KEY}}
      dd_app_key: ${{secrets.DD_APP_KEY}}