name: Verify Secrets

on:
  push:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print last 4 digits of secrets
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        run: |
          echo "DD_API_KEY (last 4): ${DD_API_KEY: -4}"
          echo "DD_APP_KEY (last 4): ${DD_APP_KEY: -4}"
