name: Verify Secrets

on:
  push:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print last 4 digits of secrets
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
        run: |
          echo "DD_API_KEY: ${DD_API_KEY:0:${#DD_API_KEY}/2} ${DD_API_KEY:${#DD_API_KEY}/2}"
          echo "DD_APP_KEY: ${DD_APP_KEY:0:${#DD_APP_KEY}/2} ${DD_APP_KEY:${#DD_APP_KEY}/2}"
